import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import Player from "@/components/player/player";
import Navbar from "@/components/navbar/navbar";
import {GoogleOAuthProvider} from "@react-oauth/google";

const inter = Poppins({
    weight: ["400", "100", "200", "300", "500", "600", "700", "800", "900"],
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode;
}) {
    return (
        <GoogleOAuthProvider clientId={process.env.AUTH_GOOGLE_ID as string}>
            <html lang="en">
            <body className={`p-[4px] pt-0 ${inter.className}`}>

            <div className={'w-[99%] h-[100vh]'}>
                <Navbar/>
                <div className={'flex w-full h-[94vh] overflow-hidden gap-2'}>
                    <Sidebar/>

                    {children}
                </div>
            </div>

            {/* Player */}
            <Player/>
            </body>

            </html>
        </GoogleOAuthProvider>
    );
}
